// Generated by CoffeeScript 1.8.0
var app, clipboard, remote, searchBox;

remote = require('remote');

app = remote.require('app');

clipboard = require('clipboard');

searchBox = $('.search-box');

$(document).on('keyup', function(e) {
  if (e.keyCode === 27) {
    searchBox.focus();
    app.emit('updateSearchResult', []);
    return app.emit('windowVisible', false);
  }
});

searchBox.on('keyup', function(e) {
  return app.emit('keyup', this.value);
});

app.on('updateSearchResult', function(results) {
  var compiled, html, resultHeight, tpl;
  tpl = $("#resultTpl").html();
  compiled = _.template(tpl);
  html = compiled({
    results: results
  });
  $('.result-part').html(html);
  resultHeight = 72 * results.length;
  if (resultHeight > 350) {
    console.log("larget");
    $('.result-part').height(350);
  }
  console.log("new height " + resultHeight);
  return app.emit('windowResultHeight', resultHeight);
});

app.on('onBrowserWindowHide', function() {
  return searchBox.val("");
});

app.on('onBrowserWindowShow', function() {
  var word;
  word = clipboard.readText('string').trim();
  if (/^\w+$/.test(word)) {
    searchBox.val(word);
    app.emit('keyup', word);
    return searchBox[0].select();
  }
});
