// Generated by CoffeeScript 1.10.0
var BrowserWindow, _, app, ce, dictLines, ec, edictParse, fs, globalShortcut, jpconv, loadDict, mainWindow, mainWindowSize, path, phoneticConvert, setBrowserVisibility, stream, xml, yodaoParser;

app = require('app');

_ = require('underscore');

fs = require('fs');

xml = require('xml2js');

path = require('path');

jpconv = require('jp-conversion');

globalShortcut = require('global-shortcut');

BrowserWindow = require('browser-window');

require('crash-reporter').start();

ec = null;

ce = null;

phoneticConvert = function(src) {
  src = src.replace(/\[.*\]/, '').split('/').map(function(ele) {
    if (ele.length !== 0) {
      return "[" + ele + "]";
    }
  }).join(' ');
  return src = src.replace(/A/g, 'æ').replace(/B/g, 'ɑ').replace(/C/g, 'ɛ').replace(/D/g, 'ː').replace(/E/g, 'ə').replace(/F/g, 'ʃ').replace(/G/g, 'ʒ').replace(/H/g, 'ɜː').replace(/I/g, 'ɪ').replace(/J/g, 'ʊ').replace(/K/g, 'ɝ').replace(/L/g, 'ɒ').replace(/M/g, 'ɚ').replace(/N/g, 'ŋ').replace(/O/g, 'ɔ').replace(/R/g, 'ʌ').replace(/S/g, 'ɝ');
};

stream = null;

dictLines = [];

loadDict = function(filename, parser, omitLineCount) {
  var lineNumber, omit, remaining, streamOptions;
  omit = omitLineCount || 0;
  streamOptions = {
    encoding: 'utf8'
  };
  stream = fs.createReadStream(__dirname + "/dict/" + filename);
  lineNumber = 0;
  remaining = '';
  stream.on('data', function(data) {
    var dictEntity, index, line, results;
    remaining += data;
    index = remaining.indexOf('\n');
    results = [];
    while (index > 1) {
      lineNumber++;
      line = remaining.substring(0, index);
      remaining = remaining.substring(index + 1);
      dictEntity = parser(line);
      dictLines.push(dictEntity);
      results.push(index = remaining.indexOf('\n'));
    }
    return results;
  });
  return stream.on('end', function() {
    var arr;
    if (remaining.length > 0) {
      dictLines.push(remaining);
      arr = line.split('\t');
      dictLines.push({
        word: arr[0],
        pron: phoneticConvert(arr[1]),
        mean: arr[2]
      });
    }
    return console.log('Load finished, ' + dictLines.length + " Lines loaded");
  });
};

yodaoParser = function(rawLine) {
  var arr;
  arr = rawLine.split('\t');
  return {
    word: arr[0],
    pron: phoneticConvert(arr[1]),
    mean: arr[2]
  };
};

edictParse = function(rawLine) {
  var arr, pron, wmatch, word;
  arr = rawLine.split('/');
  wmatch = arr[0].match(/(\S+)\s\[(\S+)\]/);
  if (wmatch) {
    pron = wmatch[2];
    word = wmatch[1];
  } else {
    pron = '';
    word = arr[0];
  }
  return {
    word: word,
    pron: pron,
    mean: arr.slice(1, arr.length - 2).join(','),
    alias: jpconv.romanise(pron || word)
  };
};

loadDict('ec.txt', yodaoParser);

loadDict('edict2u', edictParse);

mainWindow = null;

mainWindowSize = {
  height: 80,
  width: 500
};

app.on('window-all-closed', function() {
  if (process.platform !== 'darwin') {
    return app.quit();
  }
});

app.on('ready', function() {
  var showWindowHotkey;
  mainWindow = new BrowserWindow({
    width: mainWindowSize.width,
    height: mainWindowSize.height,
    "always-on-top": true,
    "skip-taskbar": false,
    frame: false
  });
  mainWindow.loadUrl("file://" + __dirname + "/index.html");
  mainWindow.on('closed', function() {
    return mainWindow = null;
  });
  mainWindow.on('blur', function() {
    return setBrowserVisibility(false);
  });
  return showWindowHotkey = globalShortcut.register('shift+ctrl+space', function() {
    return setBrowserVisibility(true);
  });
});

setBrowserVisibility = function(visibility) {
  if (visibility) {
    mainWindow.show();
    return app.emit('onBrowserWindowShow');
  } else {
    mainWindow.hide();
    return app.emit('onBrowserWindowHide');
  }
};

app.on('keyup', function(keyword) {
  var ret;
  if (keyword.length !== 0) {
    ret = _.chain(dictLines).filter(function(dict) {
      if (dict.word.indexOf(keyword.toLowerCase()) === 0) {
        return true;
      }
      if (dict.alias && dict.alias.indexOf(keyword.toLowerCase()) === 0) {
        return true;
      }
    }).first(4).value();
  } else {
    ret = [];
  }
  return app.emit('updateSearchResult', ret);
});

app.on('windowVisible', function(visibility) {
  return setBrowserVisibility(visibility);
});

app.on('windowResultHeight', function(height) {
  height += mainWindowSize.height;
  if (height > 500) {
    height = 500;
  }
  return mainWindow.setSize(mainWindowSize.width, height);
});
